language: php
sudo: false

php:
  - '5.4'
  - '5.5'
  - '5.6'

services:
  - mysql

install:
  - composer install -o

before_script:
  - mysql -e 'create database symphony_test;'

script:
  - symphony/conductor install test/travis_ci_config.php
